# Generated by Django 3.0.4 on 2020-03-09 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keygen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyUrlMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keygen.Key')),
            ],
        ),
    ]
